# Generated by Django 3.1.12 on 2024-11-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instagram', '0003_auto_20241129_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioinsta',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuarioinsta',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuarioinsta',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='usuarioinsta',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
