# Generated by Django 3.1.12 on 2024-12-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instagram', '0004_auto_20241129_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioinsta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarioinsta',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarioinsta',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarioinsta',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='usuarioinsta',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarioinsta',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usuarioinsta',
            name='usuario',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
