# Generated by Django 3.1.12 on 2024-12-05 21:34

import app_instagram.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instagram', '0006_comentario_like_publicacion_relacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioinsta',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=app_instagram.models.user_profile_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
